[en]
  title = "Miots data"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[it]
  title = "Miots data"
  languageName = "Italiano"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/it"
