[[main]]
  identifier = "about"
  name = "About me"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 2

[[main]]
  identifier = "R"
  name = "R"
  url = "R"
  weight = 3

[[main]]
  parent = "R"
  name = "Theory"
  url = "R/teoria"
  
[[main]]
  parent = "R"
  name = "My codes"
  url = "R/miei_codici"

[[main]]
  identifier = "pillole"
  name = "Pills"
  url = "pills"
  weight = 4
    
[[main]]
  parent = "pills"
  name = "Data analysis"
  url = "pills/analisi_dati"
  
[[main]]
  parent = "pills"
  name = "Science"
  url = "pills/scienza"

[[main]]
  identifier = "publications"
  name = "Publications"
  url = "publications"
  weight = 5