[[main]]
  identifier = "about"
  name = "Chi sono"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archivio"
  url = "archive"
  weight = 2

[[main]]
  identifier = "R"
  name = "R"
  url = "R"
  weight = 3

[[main]]
  parent = "R"
  name = "Teoria"
  url = "R/teoria"
  
[[main]]
  parent = "R"
  name = "I miei pacchetti"
  url = "R/miei_pacchetti"
  
[[main]]
  identifier = "bash"
  name = "Bash"
  url = "bash"
  weight = 4
  
[[main]]
  parent = "bash"
  name = "Le mie funzioni"
  url = "bash/mie_funzioni"

[[main]]
  identifier = "pillole"
  name = "Pillole"
  url = "pillole"
  weight = 5
    
[[main]]
  parent = "pillole"
  name = "Analisi dati"
  url = "pillole/analisi_dati"
  
[[main]]
  parent = "pillole"
  name = "Scienza"
  url = "pillole/scienza"

[[main]]
  identifier = "publications"
  name = "Pubblicazioni"
  url = "publications"
  weight = 6