[[main]]
  identifier = "about"
  name = "About me"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 2

[[main]]
  identifier = "R"
  name = "R"
  url = "R"
  weight = 3

[[main]]
  parent = "R"
  name = "Theory"
  url = "R/teoria"
  
[[main]]
  parent = "R"
  name = "My packages"
  url = "R/miei_pacchetti"
  
[[main]]
  identifier = "bash"
  name = "Bash"
  url = "bash"
  weight = 4
  
[[main]]
  parent = "bash"
  name = "My functions"
  url = "bash/mie_funzioni"

[[main]]
  identifier = "pillole"
  name = "Pills"
  url = "pillole"
  weight = 5
    
[[main]]
  parent = "pillole"
  name = "Data analysis"
  url = "pillole/analisi_dati"
  
[[main]]
  parent = "pillole"
  name = "Science"
  url = "pillole/scienza"

[[main]]
  identifier = "publications"
  name = "Publications"
  url = "publications"
  weight = 6